### ISSUE TITLE
Viewing Collection contents

### ISSUE THREAD

**Issue by greggunner** [flaper87/meclipse#4]
Hi Flavio,

Thanks for the plugin!

Having an issue when viewing the contents of a collection. The output tab gets created, but as soon as you expand a selection, scrollbars appear. This is correct function, however, the original container the collections were rendered into is too small. It simple looks like you just need to make the container so its attached to the parent containers.

To test this your side, I guess create a collection with only 2-3 items. Then open the collection and expand one of the entries.

Greg.

**Comment by joeymink** [comment]
Greg - glad you're giving Meclipse a try.  The collection viewer is actually implemented as an Eclipse Multipage editor.  It seems that the solution to the problem would be to use our current Composite as a child of a ScrolledComposite:

http://help.eclipse.org/helios/index.jsp?topic=/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/custom/ScrolledComposite.html

I was just playing a bit this morning, but couldn't get the ScrolledComposite to work yet.  I'll get back to this thread if I figure it out.

Side note - the collection viewer (which is an editor) is always marked dirty, which is why it immediately opens as "unsaved".  This will be fixed as well :)

**Comment by greggunner** [comment]
Joey, thats grand. Looking forward to seeing the fixes.

**Comment by greggunner** [comment]
Sorry, I clicked the wrong button for commenting :(

**Comment by joeymink** [comment]
Version 0.0.5.201107130838 is up at update.exoanalytic.com, and it fixes the vertical scrolling issue you describe.  Also fixes the always-dirty flag for the collection editor.  Unfortunately, I didn't have the time to find a solution to horizontal scrolling or wrapping for documents whose values extend to the right beyond the view width :(  Baby steps!

**Comment by greggunner** [comment]
Wicked, works well atm. :)
